notARepository: 'skip'

gui:
  scrollHeight: 8
  nerdFontsVersion: "3"
  # tokyonight theme from https://github.com/folke/tokyonight.nvim/blob/main/extras/lazygit/tokyonight_night.yml
  theme:
    activeBorderColor:
      - "#ff9e64"
      - "bold"
    inactiveBorderColor:
      - "#27a1b9"
    searchingActiveBorderColor:
      - "#ff9e64"
      - "bold"
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#283457"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    cherryPickedCommitBgColor:
      - "#bb9af7"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    markedBaseCommitBgColor:
      - "#e0af68"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#c0caf5"

git:
  paging:
    colorArgs: always
    pager: delta --dark --paging=never
  branchLogCmd: "git log --graph --color=always --pretty='%C(yellow)%h%Creset %C(auto)%d%Creset %s %Cgreen(%cr)%Creset %C(blue)<%an>%Creset' {{branchName}} --"
  allBranchesLogCmd: "git log --graph --color=always --pretty='%C(yellow)%h%Creset %C(auto)%d%Creset %s %Cgreen(%cr)%Creset %C(blue)<%an>%Creset' --all"

keybinding:
  universal:
    nextTab: '['
    prevTab: ']'
